.TH "Case.cs" 3 "Sun Mar 29 2020" "Version 2.0" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Case.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDemineur\&.Case\fP"
.br
.RI "Représente une case du démineur\&. Le grille génére sa grille en créant 'Lignes X Colonne' cases\&. Bool esTuBombe détermine si un case est une bombe ou non\&. Bool estOuverte détermine si la case est ouverte ou non\&. int nbDanger détermine combien de bombe entoure la case ouverte\&. \fBCase\fP[] casesVoisines contient les cases qui entourent cette case\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDemineur\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
