.TH "Demineur.Demineur" 3 "Sun Mar 29 2020" "Version 2.0" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.Demineur \- Point d'entrée du programme\&. On a une seule instance de \fBDemineur\fP\&. \fBDemineur\fP peut créer une seule partie à la fois\&.  

.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBDemineur\fP ()"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPartie\fP \fBm_Partie\fP"
.br
.ti -1c
.RI "\fBClassements\fP \fBm_Classement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Point d'entrée du programme\&. On a une seule instance de \fBDemineur\fP\&. \fBDemineur\fP peut créer une seule partie à la fois\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Demineur\&.Demineur\&.Demineur ()\fC [inline]\fP, \fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static void Demineur\&.Demineur\&.Main ()\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBClassements\fP Demineur\&.Demineur\&.m_Classement\fC [private]\fP"

.SS "\fBPartie\fP Demineur\&.Demineur\&.m_Partie\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
