.TH "Demineur.Partie" 3 "Sun Mar 29 2020" "Version 2.0" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.Partie
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartie\fP (string nom, short[] optionDePartie)"
.br
.ti -1c
.RI "bool \fBCommencerPartie\fP ()"
.br
.RI "S'occupe du déroulement de la partie\&. "
.ti -1c
.RI "int[] \fBTouches\fP (int iCol, int iLig, string s_Grille, int xActuel, int yActuel)"
.br
.ti -1c
.RI "void \fBAllerGauche\fP ()"
.br
.RI "En mode flèche, selectionne la case à gauche\&. "
.ti -1c
.RI "void \fBAllerDroite\fP ()"
.br
.RI "En mode flèche, selectionne la case à droite\&. "
.ti -1c
.RI "void \fBAllerHaut\fP ()"
.br
.RI "En mode flèche, selectionne la case en haut\&. "
.ti -1c
.RI "void \fBAllerBas\fP ()"
.br
.RI "En mode flèche, selectionne la case en bas\&. "
.ti -1c
.RI "bool \fBAppelerIA\fP ()"
.br
.RI "Appele l'intelligence artificiel\&. "
.ti -1c
.RI "bool \fBEntreeManuelle\fP (string entree)"
.br
.RI "Active la sélection manuelle des cases avec des coordonnées clavier\&. Saisir 'f' active la saisie avec flèches Saisir 'a' fait joueur l'\fBIA\fP si l'option de partie le permet\&. Saisir autres choses qu'un coordonnées valide entrainera une erreur\&. "
.ti -1c
.RI "bool \fBVerificationFormatDeLentree\fP (string entree)"
.br
.RI "Agit comme un masque de saisie\&. "
.ti -1c
.RI "bool \fBVerificationDesMinMaxDeLentree\fP (string entree)"
.br
.RI "Vérifie si la saisie fait partie du tableau\&. "
.ti -1c
.RI "string[] \fBInfoDepartie\fP ()"
.br
.RI "Utilise pour mettre à jour le score du joueur si la partie est gagnée\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBActiverModeFleche\fP ()"
.br
.RI "Active la sélection des cases avec les flèches\&. "
.ti -1c
.RI "void \fBActiverModeSaisieManuelle\fP ()"
.br
.RI "Active la sélection des cases avec les flèches\&. "
.ti -1c
.RI "bool \fBVerificationOuvertureEtContenue\fP (int[] \fBselection\fP)"
.br
.RI "Une fois la saisie validé, une ouvre la case si elle n'est pas déjà ouverte\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Regex \fBrx\fP = new Regex(@'^\\d+\\s\\d+$', RegexOptions\&.Compiled | RegexOptions\&.IgnoreCase)"
.br
.ti -1c
.RI "int[] \fBpositionActuelle\fP"
.br
.ti -1c
.RI "int[] \fBselection\fP"
.br
.ti -1c
.RI "\fBGrille\fP \fBm_Grille\fP"
.br
.ti -1c
.RI "bool \fBenMarche\fP"
.br
.ti -1c
.RI "bool \fBmort\fP"
.br
.ti -1c
.RI "bool \fBauto\fP"
.br
.ti -1c
.RI "\fBJoueur\fP \fBj\fP"
.br
.ti -1c
.RI "string \fBdifficulte\fP"
.br
.ti -1c
.RI "string \fBtemps\fP"
.br
.ti -1c
.RI "string \fBgrosseur\fP"
.br
.ti -1c
.RI "\fBAITest\fP \fBintel\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Demineur\&.Partie\&.Partie (string nom, short[] optionDePartie)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Demineur\&.Partie\&.ActiverModeFleche ()\fC [inline]\fP, \fC [private]\fP"

.PP
Active la sélection des cases avec les flèches\&. 
.SS "void Demineur\&.Partie\&.ActiverModeSaisieManuelle ()\fC [inline]\fP, \fC [private]\fP"

.PP
Active la sélection des cases avec les flèches\&. 
.SS "void Demineur\&.Partie\&.AllerBas ()\fC [inline]\fP"

.PP
En mode flèche, selectionne la case en bas\&. 
.SS "void Demineur\&.Partie\&.AllerDroite ()\fC [inline]\fP"

.PP
En mode flèche, selectionne la case à droite\&. 
.SS "void Demineur\&.Partie\&.AllerGauche ()\fC [inline]\fP"

.PP
En mode flèche, selectionne la case à gauche\&. 
.SS "void Demineur\&.Partie\&.AllerHaut ()\fC [inline]\fP"

.PP
En mode flèche, selectionne la case en haut\&. 
.SS "bool Demineur\&.Partie\&.AppelerIA ()\fC [inline]\fP"

.PP
Appele l'intelligence artificiel\&. 
.PP
\fBReturns\fP
.RS 4
bool : vrai si \fBIA\fP actif, faux si partie sans \fBIA\fP
.RE
.PP

.SS "bool Demineur\&.Partie\&.CommencerPartie ()\fC [inline]\fP"

.PP
S'occupe du déroulement de la partie\&. 
.PP
\fBReturns\fP
.RS 4
bool : vrai si gagnée, faux si perdu\&.
.RE
.PP

.SS "bool Demineur\&.Partie\&.EntreeManuelle (string entree)\fC [inline]\fP"

.PP
Active la sélection manuelle des cases avec des coordonnées clavier\&. Saisir 'f' active la saisie avec flèches Saisir 'a' fait joueur l'\fBIA\fP si l'option de partie le permet\&. Saisir autres choses qu'un coordonnées valide entrainera une erreur\&. 
.PP
\fBParameters\fP
.RS 4
\fIentree\fP Saisie du joueur\&.
.RE
.PP
\fBReturns\fP
.RS 4
bool : Retourne true si saisie valide, false si invalide\&.
.RE
.PP

.SS "string [] Demineur\&.Partie\&.InfoDepartie ()\fC [inline]\fP"

.PP
Utilise pour mettre à jour le score du joueur si la partie est gagnée\&. 
.PP
\fBReturns\fP
.RS 4
string[] : Informations de partie {nom_joueur, grosseur, difficulté, temps}
.RE
.PP

.SS "int [] Demineur\&.Partie\&.Touches (int iCol, int iLig, string s_Grille, int xActuel, int yActuel)\fC [inline]\fP"

.SS "bool Demineur\&.Partie\&.VerificationDesMinMaxDeLentree (string entree)\fC [inline]\fP"

.PP
Vérifie si la saisie fait partie du tableau\&. 
.PP
\fBParameters\fP
.RS 4
\fIentree\fP Saisie manuelle du l'utilisateur\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "bool Demineur\&.Partie\&.VerificationFormatDeLentree (string entree)\fC [inline]\fP"

.PP
Agit comme un masque de saisie\&. 
.PP
\fBParameters\fP
.RS 4
\fIentree\fP Saisie manuelle du l'utilisateur\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "bool Demineur\&.Partie\&.VerificationOuvertureEtContenue (int[] selection)\fC [inline]\fP, \fC [private]\fP"

.PP
Une fois la saisie validé, une ouvre la case si elle n'est pas déjà ouverte\&. 
.PP
\fBParameters\fP
.RS 4
\fIselection\fP 
.RE
.PP
\fBReturns\fP
.RS 4
bool : vrai si case a été ouverte, faux si case déjà ouverte\&.
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "bool Demineur\&.Partie\&.auto\fC [private]\fP"

.SS "string Demineur\&.Partie\&.difficulte\fC [private]\fP"

.SS "bool Demineur\&.Partie\&.enMarche\fC [private]\fP"

.SS "string Demineur\&.Partie\&.grosseur\fC [private]\fP"

.SS "\fBAITest\fP Demineur\&.Partie\&.intel\fC [private]\fP"

.SS "\fBJoueur\fP Demineur\&.Partie\&.j\fC [private]\fP"

.SS "\fBGrille\fP Demineur\&.Partie\&.m_Grille\fC [private]\fP"

.SS "bool Demineur\&.Partie\&.mort\fC [private]\fP"

.SS "int [] Demineur\&.Partie\&.positionActuelle\fC [private]\fP"

.SS "Regex Demineur\&.Partie\&.rx = new Regex(@'^\\d+\\s\\d+$', RegexOptions\&.Compiled | RegexOptions\&.IgnoreCase)\fC [private]\fP"

.SS "int [] Demineur\&.Partie\&.selection\fC [private]\fP"

.SS "string Demineur\&.Partie\&.temps\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
