.TH "Demineur.IA" 3 "Sun Mar 29 2020" "Version 2.0" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.IA
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIA\fP (int lignes, int colonnes)"
.br
.ti -1c
.RI "int[] \fBJouerTour\fP (string grille)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "FileInfo \fBdll\fP"
.br
.ti -1c
.RI "Type[] \fBclasses\fP"
.br
.ti -1c
.RI "object[] \fBligCol\fP"
.br
.ti -1c
.RI "dynamic \fBbot\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Demineur\&.IA\&.IA (int lignes, int colonnes)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int [] Demineur\&.IA\&.JouerTour (string grille)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "dynamic Demineur\&.IA\&.bot\fC [private]\fP"

.SS "Type [] Demineur\&.IA\&.classes\fC [private]\fP"

.SS "FileInfo Demineur\&.IA\&.dll\fC [private]\fP"

.SS "object [] Demineur\&.IA\&.ligCol\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
