.TH "Demineur.Menu" 3 "Sun Mar 29 2020" "Version 2.0" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.Menu \- La classe \fBMenu\fP guide l'utilisateur à travers les différentes options de partie\&. Il peut \fBJoueur\fP, afficher le classement ou quitter\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static short \fBAfficherMenu\fP ()"
.br
.RI "Dessine la Première page du menu principale\&. "
.ti -1c
.RI "static short \fBAfficherClassement\fP (string p_Classement, short tri)"
.br
.RI "Dessine le classement\&. "
.ti -1c
.RI "static short[] \fBOptionDePartie\fP ()"
.br
.RI "Retourne le tableau d'options de partie\&. Est appelé lors dela création d'une nouvelle partie\&. "
.ti -1c
.RI "static string \fBDemanderNom\fP ()"
.br
.RI "Demande le nom du joueur après qu'il ait confirmer le début de la partie\&. Est appelé lors dela création d'une nouvelle partie\&. "
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static short \fBMenuJouerGrosseur\fP ()"
.br
.RI "S'affiche lorsque le joueur choisi de jouer\&. Permet de choisir la grosseur du plateau "
.ti -1c
.RI "static short \fBMenuJouerDifficulte\fP ()"
.br
.RI "S'affiche lorsque le joueur a choisi la grosseur du plateau\&. Permet de choisir la difficulté de la partie\&. "
.ti -1c
.RI "static short \fBMenuJouerAI\fP ()"
.br
.RI "S'affiche lorsque le joueur a choisi sa difficulté\&. Permet de choisir l'aide de l'intelligence artificiel\&. "
.ti -1c
.RI "static short \fBRecapFinal\fP ()"
.br
.RI "S'affiche lorsque le joueur a choisi le type d'assistance désiré\&. Le joueur voit ce qu'il a sélectionné\&. Il peut commencer la partie ou modifier les options de partie\&. "
.ti -1c
.RI "static string \fBTypeDeTri\fP (short tri)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static short[] \fBoptionsDePartie\fP"
.br
.ti -1c
.RI "static string \fBrecap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
La classe \fBMenu\fP guide l'utilisateur à travers les différentes options de partie\&. Il peut \fBJoueur\fP, afficher le classement ou quitter\&. 


.SH "Member Function Documentation"
.PP 
.SS "static short Demineur\&.Menu\&.AfficherClassement (string p_Classement, short tri)\fC [inline]\fP, \fC [static]\fP"

.PP
Dessine le classement\&. 
.SS "static short Demineur\&.Menu\&.AfficherMenu ()\fC [inline]\fP, \fC [static]\fP"

.PP
Dessine la Première page du menu principale\&. 
.PP
\fBReturns\fP
.RS 4
Short : Retourne le choix 1 : jouer 2 : Afficher le classement 3 : Quitter 
.RE
.PP

.SS "static string Demineur\&.Menu\&.DemanderNom ()\fC [inline]\fP, \fC [static]\fP"

.PP
Demande le nom du joueur après qu'il ait confirmer le début de la partie\&. Est appelé lors dela création d'une nouvelle partie\&. 
.PP
\fBReturns\fP
.RS 4
string : nom
.RE
.PP

.SS "static short Demineur\&.Menu\&.MenuJouerAI ()\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.PP
S'affiche lorsque le joueur a choisi sa difficulté\&. Permet de choisir l'aide de l'intelligence artificiel\&. 
.PP
\fBReturns\fP
.RS 4
short : Retourne le choix 1 : Sans 2 : Avec 3 : Automatique 
.RE
.PP

.SS "static short Demineur\&.Menu\&.MenuJouerDifficulte ()\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.PP
S'affiche lorsque le joueur a choisi la grosseur du plateau\&. Permet de choisir la difficulté de la partie\&. 
.PP
\fBReturns\fP
.RS 4
short : Retourne le choix 1 : Facile 2 : Normal 3 : Difficile 
.RE
.PP

.SS "static short Demineur\&.Menu\&.MenuJouerGrosseur ()\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.PP
S'affiche lorsque le joueur choisi de jouer\&. Permet de choisir la grosseur du plateau 
.PP
\fBReturns\fP
.RS 4
short : Retourne le choix 1 : Petit 2 : Moyen 3 : Grand 
.RE
.PP

.SS "static short [] Demineur\&.Menu\&.OptionDePartie ()\fC [inline]\fP, \fC [static]\fP"

.PP
Retourne le tableau d'options de partie\&. Est appelé lors dela création d'une nouvelle partie\&. 
.PP
\fBReturns\fP
.RS 4
short[] optionsDePartie
.RE
.PP

.SS "static short Demineur\&.Menu\&.RecapFinal ()\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.PP
S'affiche lorsque le joueur a choisi le type d'assistance désiré\&. Le joueur voit ce qu'il a sélectionné\&. Il peut commencer la partie ou modifier les options de partie\&. 
.PP
\fBReturns\fP
.RS 4
short : Retourne le choix C : Commencer -> retourne 0 4 : Recommencer 
.RE
.PP

.SS "static string Demineur\&.Menu\&.TypeDeTri (short tri)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "short [] Demineur\&.Menu\&.optionsDePartie\fC [static]\fP, \fC [private]\fP"

.SS "string Demineur\&.Menu\&.recap\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
