.TH "Grille.cs" 3 "Sun Mar 29 2020" "Version 2.0" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Grille.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDemineur\&.Grille\fP"
.br
.RI "\fBGrille\fP représente le plateau de jeu\&. Elle contient des cases de type \fBCase\fP\&. \fBCase\fP[,] : champs est le tableau 2D [Lignes x Colonnes] Int : nbBombeGrille contient le nombre de bombe que la grille contient\&. Int : colonnes Dimension X du tableau Int : lignes Dimension Y du table Int : casesFermer contient le nombre de base fermer en début de partie\&. Stack<Case> : aOuvrir Permet la recherche récursive pour l'ouverture automatique des cases dont le danger est de 0\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDemineur\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
