.TH "Demineur.Joueur" 3 "Tue Mar 10 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.Joueur
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJoueur\fP (string p_Nom)"
.br
.ti -1c
.RI "string \fBObtenirNom\fP ()"
.br
.ti -1c
.RI "string[] \fBObtenirScore\fP (string p_Nom)"
.br
.ti -1c
.RI "bool \fBModifierScore\fP (char grosseur, char difficulte, string temps)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Demineur\&.Joueur\&.Joueur (string p_Nom)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool Demineur\&.Joueur\&.ModifierScore (char grosseur, char difficulte, string temps)\fC [inline]\fP"

.SS "string Demineur\&.Joueur\&.ObtenirNom ()\fC [inline]\fP"

.SS "string [] Demineur\&.Joueur\&.ObtenirScore (string p_Nom)\fC [inline]\fP"

.SS "override string Demineur\&.Joueur\&.ToString ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
