.TH "Demineur.Classements" 3 "Thu Mar 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.Classements
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassements\fP ()"
.br
.ti -1c
.RI "void \fBAfficherClassement\fP ()"
.br
.ti -1c
.RI "void \fBMettreAJourJoueuer\fP (string NomJoueur, string Temps, string Difficulte)"
.br
.ti -1c
.RI "void \fBFichierClassement\fP ()"
.br
.RI "Est appelé lors de la construction de Classement\&. Créer la liste de joueur si le fichier text existe\&. Créer un fichier text vide si il n'existe pas\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Demineur\&.Classements\&.Classements ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Demineur\&.Classements\&.AfficherClassement ()\fC [inline]\fP"

.SS "void Demineur\&.Classements\&.FichierClassement ()\fC [inline]\fP"

.PP
Est appelé lors de la construction de Classement\&. Créer la liste de joueur si le fichier text existe\&. Créer un fichier text vide si il n'existe pas\&. 
.SS "void Demineur\&.Classements\&.MettreAJourJoueuer (string NomJoueur, string Temps, string Difficulte)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
