.TH "Demineur.Grille" 3 "Tue Mar 10 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.Grille
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGrille\fP (short colonne, short ligne, short nbBombe)"
.br
.ti -1c
.RI "void \fBDisperserBombes\fP ()"
.br
.ti -1c
.RI "void \fBRencontreVoisin\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Demineur\&.Grille\&.Grille (short colonne, short ligne, short nbBombe)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Demineur\&.Grille\&.DisperserBombes ()\fC [inline]\fP"

.SS "void Demineur\&.Grille\&.RencontreVoisin ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
