.TH "Demineur.Classements" 3 "Tue Mar 10 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.Classements
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassements\fP ()"
.br
.ti -1c
.RI "void \fBAfficherClassement\fP ()"
.br
.ti -1c
.RI "void \fBMettreAJour\fP (string NomJoueur, string Temps, string Difficulte)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Demineur\&.Classements\&.Classements ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Demineur\&.Classements\&.AfficherClassement ()\fC [inline]\fP"

.SS "void Demineur\&.Classements\&.MettreAJour (string NomJoueur, string Temps, string Difficulte)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
