.TH "Demineur.Case" 3 "Tue Mar 10 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.Case
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCase\fP ()"
.br
.ti -1c
.RI "void \fBCombienDanger\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "short \fBValue\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBBombe\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCase\fP \fBthis[int i]\fP\fC [set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Demineur\&.Case\&.Case ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Demineur\&.Case\&.CombienDanger ()\fC [inline]\fP"

.SH "Property Documentation"
.PP 
.SS "bool Demineur\&.Case\&.Bombe\fC [get]\fP, \fC [set]\fP"

.SS "\fBCase\fP Demineur\&.Case\&.this[int i]\fC [set]\fP"

.SS "short Demineur\&.Case\&.Value\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
