.TH "Demineur.Partie" 3 "Tue Mar 10 2020" "Demineur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Demineur.Partie
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartie\fP (char[] optionDePartie)"
.br
.ti -1c
.RI "string \fBObtenirMetadonneesDeLaPartieActuellementTerminee\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Demineur\&.Partie\&.Partie (char[] optionDePartie)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "string Demineur\&.Partie\&.ObtenirMetadonneesDeLaPartieActuellementTerminee ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Demineur from the source code\&.
