.TH "IA.cs" 3 "Thu Mar 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IA.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDemineur\&.IA\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDemineur\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
